### ISSUE TITLE
Add document markers

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#1]
It would be nice to have the ability to document the CRDs as we develop the workload manifests.  This would give us the ability to have the `kubectl explain` feature for all of our custom resources that we spit out and would be self-documenting for the end user of operator builder:

This was the decided upon implementation for workload-docs (see new `#+workload-doc` marker):

```yaml
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: default
  annotations:
    workload.cnr.vmware.com/resource-name: default-limit-range
spec:
  limits:
    - default:
        #+workload-doc: 
        #   this is the documentation for the next found value
        cpu: "50m" #+workload:defaultNamespaceLimitsCpu:default="50m":type=string
        #+workload-doc: 
        #   this is the documentation for the next found value
        memory: "64Mi" #+workload:defaultNamespaceLimitsMemory:default="64Mi":type=string
      defaultRequest:
        cpu: "50m" #+workload:defaultNamespaceRequestsCpu:default="50m":type=string
        memory: "64Mi" #+workload:defaultNamespaceRequestsMemory:default="64Mi":type=string
      max:
        cpu: "200m" #+workload:defaultNamespaceMaxLimitsCpu:default="200m":type=string
        memory: "512Mi" #+workload:defaultNamespaceMaxLimitsMemory:default="512Mi":type=string
      type: Container
```

In order to implement this, the `*_types.go` file needs to inject a comment above the definition, like so:

```go
	// +kubebuilder:default="k8s.gcr.io/autoscaling/vpa-admission-controller:0.9.0"
	// +kubebuilder:validation:Optional
	// VpaWebhookImage this is a test
	VpaWebhookImage string `json:"vpaWebhookImage"`
```

This will produce a CRD that has the following:

```yaml
              vpaWebhookImage:
                default: k8s.gcr.io/autoscaling/vpa-admission-controller:0.9.0
                description: VpaWebhookImage this is a test
                type: string
```
