### ISSUE TITLE
Refactor workload config

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#102]
Today a worklaod config looks as follows:

```
name: webstore
kind: StandaloneWorkload
spec:
  domain: acme.com
  apiGroup: apps
  apiVersion: v1alpha1
  apiKind: WebStore
  clusterScoped: false
  companionCliRootcmd:
    name: webstorectl
    description: Manage webstore stuff like a boss
  resources:
  - app.yaml
```
But really, we should have the API fields nested together like this:

```
name: webstore
kind: StandaloneWorkload
spec:
  api:
    domain: acme.com
    group: apps
    version: v1alpha1
    kind: WebStore
    clusterScoped: false
  companionCliRootcmd:
    name: webstorectl
    description: Manage webstore stuff like a boss
  resources:
  - app.yaml
```
