### ISSUE TITLE
Implement suport for multiple API versions

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#106]
Allow developers to define multiple API versions in their workload configs.  Today we support the following:

```yaml
name: webstore
kind: StandaloneWorkload
spec:
  api:
    domain: acme.com
    group: apps
    version: v1alpha1
    kind: WebStore
    clusterScoped: false
  companionCliRootcmd:
    name: webstorectl
    description: Manage webstore stuff like a boss
  resources:
  - app.yaml
```
We could support it with something like:

```yaml
name: webstore
kind: StandaloneWorkload
spec:
  api:
    domain: acme.com
    group: apps
    kind: WebStore
    versions:
      - version: v1alpha1
        deprecated: true
        unsupported: true
      - version: v1beta1
        deprecated: true
      - version: v1beta2
    clusterScoped: false
  companionCliRootcmd:
    name: webstorectl
    description: Manage webstore stuff like a boss
  resources:
  - app.yaml
```
