### ISSUE TITLE
Support multiple collections per cluster

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#107]
Today we have no mechanism to tie components to collections and so are enforcing one collection per cluster.

It will be a common requirement to support multiple collections so we'll need to add something like the `collectionRef` to the components:

```yaml
apiVersion: ingress.acme.com/v1alpha1
kind: Contour
metadata:
  name: contour-sample
spec:
  EnvoyImage: nginx:1.17
  namespace: ingress-system
  contourReplicas: 3
  contourImage: nginx:1.17
  collectionRef:
    kind: CloudNativePlatform
    apiVersion: platforms.acme.com/v1alpha2
    name: cloudnativeplatform-sample
```

**Comment by vrabbi** [comment]
any idea when this will be implemented? currently this is a blocker for me to use this project which otherwise seems really useful for my use cases

**Comment by lander2k2** [comment]
@vrabbi I've added this issue to our next release project.  We'll prioritize this as it has popped up a couple of times now.  Should be able to release this feature in the next couple of weeks, I'd say.

**Comment by vrabbi** [comment]
Awesome! Cant wait! Ive got a bunch of ideas on operators i want to build and this tools seems amazing!

**Comment by scottd018** [comment]
@lander2k2 also take a look at this comment https://github.com/vmware-tanzu-labs/operator-builder/issues/178#issuecomment-967051778 which will affect the implementation for collections.  I think the big "how do we do this" is what information we want to key off of.  @JefeDavis and i had an adhoc conversation about it and I put the outcome of that conversation in the linked comment.

**Comment by lander2k2** [comment]
Consensus is to implement with a mutating webhook so that when a component like this is created:
```yaml
apiVersion: ingress.acme.com/v1alpha1
kind: Contour
metadata:
  name: contour-sample
spec:
  namespace: "ingress-system"
  envoyImage: "nginx:1.17"
  collection:
    name: cnp-sample
    namespace: platform-system  # if applicable
```
... the mutating webhook adds an owner reference on the component.
