### ISSUE TITLE
Domain Spec field on workload collection isn't being used

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#11]
When initializing a project with operator-builder, the `domain` spec field should allow the operator-builder command to be run without the `--domain` flag.  However, it fails with a missing go.mod.

Spec:

```yaml
name: cloud-native-platform
kind: WorkloadCollection
spec:
  domain: acme.com
  apiGroup: platforms
  apiVersion: v1alpha1
  apiKind: CloudNativePlatform
  clusterScoped: true
  companionCliRootcmd:
    name: cnpctl
    description: Manage platform stuff like a boss
  componentFiles:
  - ns-operator-component.yaml
  - contour-component.yaml
 ```

Error:

```bash
TEST_PATH=/tmp/test TEST_SCRIPT=platform.sh make test
go build -o bin/operator-builder cmd/main.go
cp bin/operator-builder /usr/local/bin/operator-builder
mkdir /tmp/test/.test
cp test/platform.sh /tmp/test/.test/
(cd /tmp/test; ./.test/platform.sh)
Error: failed to initialize project: unable to inject the configuration to "base.go.kubebuilder.io/v3": error finding current repository: could not determine repository path from module data, package data, or by initializing a module: go: cannot determine module path for source directory /tmp/test (outside GOPATH, module path must be specified)

Example usage:
        'go mod init example.com/m' to initialize a v0 or v1 module
        'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
```

Only way around that is to manually initialize the go.mod.
