### ISSUE TITLE
[Bug] New API Spec Unmarshal Errors

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#111]
The following error occurs when trying to unmarshal with the new API spec format:

```
Error: failed to initialize project: unable to inject the configuration to "config.operatorbuilder.io/v1": failed to read file .source/cnpo.tanzulabs.vmware.com/collection.yaml: yaml: unmarshal errors:
  line 7: field apiGroup not found in type v1.APISpec
  line 8: field apiVersion not found in type v1.APISpec
  line 9: field apiKind not found in type v1.APISpec
Usage:
  operator-builder init [flags]
```

The collection:

```yaml
---
name: cloud-native-platform
kind: WorkloadCollection
spec:
  api:
    domain: cnpo.tanzulabs.vmware.com
    apiGroup: platform
    apiVersion: v1alpha1
    apiKind: CloudNativePlatform
    clusterScoped: true
  companionCliRootcmd:
    name: cnpo
    description: Manage Cloud Native Platform Operator
  componentFiles:
...
```
