### ISSUE TITLE
Need to be able to create resources with a workload collection

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#138]
Currently, we cannot include resources with a `WorkloadCollection` like this:

```
---
name: spring-petclinic
kind: WorkloadCollection
spec:
  api:
    domain: demo.com
    group: apps
    version: v1alpha1
    kind: PetClinic
    clusterScoped: true
  companionCliRootcmd:
    name: petctl
    description: Deploys a the Pet Clinic Springboot application
  resources:
  - 01-namespace.yaml
  - 02-config-map.yaml
  - 03-role.yaml
  componentFiles:
  - wavefront-workload.yaml
  - gateway-workload.yaml
  - customers-workload.yaml
  - vets-workload.yaml
  - visits-workload.yaml
```
