### ISSUE TITLE
[Bug] operator-builder create api fails if companionCliRootcmd not included in workload spec

### ISSUE THREAD

**Issue by mrporcles** [vmware-tanzu-labs/operator-builder#140]
operator-builder create api fails if companionCliRootcmd not included in workload spec. https://github.com/vmware-tanzu-labs/operator-builder#step-3 in the README seems to indicate that companionCliRootcmd can be optional in the workload spec but if not included it will fail to execute `operator-builder create api`.

Example workload manifest:

```yaml
name: spring-petclinic
kind: StandaloneWorkload
spec:
  api:
    domain: demo.com
    group: apps
    version: v1alpha1
    kind: SpringPetClinic
    clusterScoped: true
  resources:
  - 01-namespace.yaml
  - 02-config-map.yaml
  - 03-role.yaml
  - 04-wavefront.yaml
  - 05-api-gateway-service.yaml
  - 06-api-gateway-deployment.yaml
  - 07-customers-db-mysql.yaml
  - 08-customers-service-service.yaml
  - 09-customers-service-deployment.yaml
  - 10-vets-db-mysql.yaml
  - 11-vets-service-service.yaml
  - 12-vets-service-deployment.yaml
  - 13-visits-db-mysql.yaml
  - 14-visits-service-service.yaml
  - 15-visits-service-deployment.yaml
 ```

Execution output:

```bash
operator-builder create api --workload-config .source-manifests/workload.yaml --controller --resource
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
apis/apps/v1alpha1/springpetclinic_types.go
controllers/apps/springpetclinic_controller.go
Building API...
Error: failed to create API: unable to scaffold with "workload.operatorbuilder.io/v1": error updating root.go: open cmd/commands/root.go: no such file or directory
```
