### ISSUE TITLE
bug: companion cli missing default values

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#145]
When using the companion CLI, default values are not generated in the child manifests:

This command:

```bash
bin/webstorectl generate -w ~/VSCode/scottd018-github/operator-builder/test/application/.workloadConfig/workload.yaml
```

Results in:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstore-deploy
spec:
  replicas: 0   <<<<<< 0 REPLICAS
  selector:
    matchLabels:
      app: webstore
  template:
    metadata:
      labels:
        app: webstore
    spec:
      containers:
      - image: ""   <<<<<<<< NO IMAGE
        name: webstore-container
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: webstore-ing
spec:
  rules:
  - host: app.acme.com
    http:
      paths:
      - backend:
          serviceName: webstorep-svc
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: ""   <<<<<<<< NO SERVICE NAME
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webstore
```
