### ISSUE TITLE
feat: default companion cli fields

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#148]
Currently, we expect a bunch of companion CLI fields in the workload configuration:

```yaml
  companionCliRootcmd:
    name: webstorectl
    description: Manage webstore stuff like a boss
  companionCliSubcmd:
    name: subcommand
    description: Manage subcommand stuff like a boss
```

This causes some complex logic in the generation code that causes problems such as #140 .

We should default these values to the `kind` field of the workload configuration:

```yaml
  api:
    group: ingress
    version: v1alpha1
    kind: Contour.  <<<< use this field which would be `contour` if unspecified
    clusterScoped: true
```

This means that the companionCli is always going to be generated and available to consumers of operator-builder and simplifies the codebase.
