### ISSUE TITLE
Feature: Workload Collection as a Global Parameter Store

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#15]
As a platform user, I want to be able to use the parent `WorkloadCollection` resource as a way to share common variables across the `ComponentWorkloads`.  A good example of this is using the same `ingressDomain` for each of the ingress resources, or a single `ClusterIssuer` name to issue all of the certificates within the cluster.

Here is a mockup of what this could look like in a workload collection resource (see `globalVariables`):

```yaml
---
name: cloud-native-platform
kind: WorkloadCollection
spec:
  domain: cnpo.tanzulabs.vmware.com
  apiGroup: platform
  apiVersion: v1alpha1
  apiKind: CloudNativePlatform
  clusterScoped: true
  companionCliRootcmd:
    name: cnpo
    description: Manage Cloud Native Platform Operator
  globalVariables:
    - name: ingressDomain
       type: string
       default: "example.com"
    - name: certIssuerName
       type: string
       default: "self-signed"    
  componentFiles:
    - tenancy/common/workload.yaml
    - tenancy/namespace-operator/workload.yaml
 ```

Additionally, rather than having the user write custom logic to use the global variable store and mutate the resources, would like a way to automatically inject those values into `ComponentWorkload` manifests.

Another mockup of what it may look like:

```yaml
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dex #+workload:dexResourceName:default="dex":type=string
  namespace: tanzu-identity #+workload:namespace:default="tanzu-identity":type=string
spec:
  secretName: dex-cert-tls
  commonName: dex #+workload:dexResourceName:default="dex":type=string
  dnsNames:
    - dex #+workload:dexResourceName:default="dex":type=string
    - oidc-server.example.com #+workload:dexDns:default="oidc-server.example.com":type=string
  ipAddresses:
    - "127.0.0.1"
  duration: "2160h0m0s"
  renewBefore: "360h0m0s"
  organization:
    - "vmware"
  keySize: 4096
  keyAlgorithm: "rsa"
  keyEncoding: "pkcs1"
  issuerRef:
    name: "self" #+workload:clusterIssuerName:default=$certIssuerName:type=globalVariable
    kind: "ClusterIssuer"
```
