### ISSUE TITLE
Conflicting default values on workload markers not being checked

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#16]
In the following example...
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webstore-ing
  label:
    team: team-x  # +workload:resourceLabel:default=team-x:type=string
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.acme.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webstorep-svc
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webstore-svc
  label:
    team: team-y  # +workload:resourceLabel:default=team-y:type=string
spec:
  selector:
    app: webstore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
```
... the `resourceLabel` field is used twice but with different default values.  Currently operator builder will use the first default value it encounters and ignore the rest.  We should catch this and return an error to the user without creating the API.
