### ISSUE TITLE
feat: allow `resources` field to point to a directory rather than an individual file

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#166]
Given this tree:

```bash
operator-builder/
├── resource3.yaml
└── resources
    ├── resource1.yaml
    └── resource2.yaml
```

And this configruation:

```yaml
name: webstore
kind: StandaloneWorkload
spec:
  api:
    domain: acme.com
    group: apps
    version: v1alpha1
    kind: WebStore
    clusterScoped: false
  companionCliRootcmd:
    name: webstorectl
    description: Manage webstore stuff like a boss
  resources:
  - operator-builder/resources
  - operator-builder/resource3.yaml
```

We would consume the following files:

```bash
operator-builder/resources/resource1.yaml
operator-builder/resources/resource2.yaml
operator-builder/resource3.yaml
```
