### ISSUE TITLE
Add namespace field to namespace-scoped sample manifests in generated codebases

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#167]
Namespace vs cluster scoping for resources can be confusing for users at times.  In an effort to reduce confusion I propose we should add the namespace field with `namespace: default` for all namespace-scoped resources.  For example:
```
apiVersion: apps.acme.com/v1alpha1
kind: WebStore
metadata:
  name: webstore-sample
  namespace: default
spec:
  webStoreReplicas: 2
  webstoreImage: "nginx:1.17"
  serviceName: "webstore-svc"
```
