### ISSUE TITLE
bug: reconcile on collection changes

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#178]
Currently, we do not reconcile workloads when its parent collection changes.

Idea:

 - Add a watch to the collection resource

Depends on #67

**Comment by JefeDavis** [comment]
@scottd018 is this actually dependent on #67 or can this be done in parallel?

**Comment by scottd018** [comment]
@JefeDavis I believe they can be done in parallel. I think the better term would have been “affects” rather than “depends upon”. I just threw that issue out there before I forgot and didn't put much thought into it…ha

**Comment by scottd018** [comment]
This will be highly dependent upon the implementation of #107 .  We will have to find a way to determine which component we are reconciling for which collection and/or find a way to tell the component to reconcile only when a specific collection changes.  These 2 tasks should likely be linked together as one.

The different scenarios that we came up with to link a component to a collection are:

1. GVK
2. Labels
3. Annotations
4. Namespace/Name

My preference would be 4, as that is how the controller is currently deciding how to reconcile against its resources today (see https://github.com/vmware-tanzu-labs/operator-builder/blob/main/internal/plugins/workload/v1/scaffolds/templates/controller/controller.go#L116 `req.NamespacedName`).

**Comment by lander2k2** [comment]
I had previously envisioned a component having a `collectionRef` section added to it's spec.  Something like this:
```yaml
apiVersion: ingress.acme.com/v1alpha1
kind: Contour
metadata:
  name: contour-sample
spec:
  namespace: "ingress-system"
  envoyImage: "nginx:1.17"
  collectionRef:
    apiVersion: platforms.acme.com/v1alpha1
    kind: CloudNativePlatform
    name: cnp-sample
    namespace: cnp-system  # no namespace if cluster-scoped
```
However, maybe we can just solve this by making the collection the owner of the components.  The `ownerReference` takes care of all that for us.  And I think we want the behavior that comes with it anyway.
