### ISSUE TITLE
feat: complex data types []map[string]string/int/bool

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#184]
Add []map[string]string/int/bool complex data type.

**Comment by scottd018** [comment]
The solution to this problem may be solved in the description to issue https://github.com/vmware-tanzu-labs/operator-builder/issues/231.  We decided to keep the fix to that issue simple meanwhile solving this, more complicated issue, here.

**Comment by scottd018** [comment]
As a reminder to the above, here is the discussion from the issue:

Consider the following custom resource.  When this resource is created, the controller would create two CronJobs to run at the scheduled time and scale the sample-deploy Deployment to the given number of replicas:
```yaml
apiVersion: autoscaling.containers.myorg.com/v1alpha1
kind: PodScalingSchedule
metadata:
  name: sample
  namespace: pss
spec:
  targetReference:
    name: sample-deploy
    kind: Deployment
    apiVersion: apps/v1
  scaleOperations:
  - schedule: "54 12 * * *"
    replicas: "2"
  - schedule: "55 12 * * *"
    replicas: "5"
```
So we will need to create a CronJob resource for each object in `spec.scaleOperations` array.

We could possibly use a source manifest with a marker that indicates that field name `scaleOperations` needs to be an array.  See example of proposed marker on line one:
```yaml
# +operator-builder:field:name=scaleOperations,contains=array
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-scaling-schedule  # +operator-builder:field:name=targetReference.name,type=string
spec:
  schedule: "27 16 * * *"  # +operator-builder:field:name=scaleOperations.schedule,type=string
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: sample-scaling-schedule  # +operator-builder:field:name=targetReference.name,type=string,replace="sample"
          containers:
          - name: sample-scaling-schedule  # +operator-builder:field:name=targetReference.name,type=string,replace="sample"
            image: lander2k2/deploy-update:0.1.0
            imagePullPolicy: IfNotPresent
            command:
            - bash
            args:
            - /update-deployment.sh
            - deployment  # +operator-builder:field:name=targetReference.kind,type=string
            - curfew-sample  # +operator-builder:field:name=targetReference.name,type=string
            - "2"  # +operator-builder:field:name=scaleOperations.replicas,type=string
```
And then we would need to generate CreateFunc that returns an _array_ of `client.Object` and looks something like this:
```go
// CreateCronJobTargetReferenceName creates the CronJob resources.
func CreateCronJobTargetReferenceName(
	parent *autoscalingv1alpha1.PodScalingSchedule,
	transferLabels map[string]string,
	updateImage string,
) ([]client.Object, error) {
	resourceObjects := []client.Object{}

	for n, scaleOp := range parent.Spec.ScaleOperations {
		var resourceObj = &unstructured.Unstructured{
			Object: map[string]interface{}{
				"apiVersion": "batch/v1beta1",
				"kind":       "CronJob",
				"metadata": map[string]interface{}{
					"name":   "" + parent.Spec.TargetReference.Name + "-scaling-schedule-" + strconv.Itoa(n),
					"labels": transferLabels,
				},
				"spec": map[string]interface{}{
					"schedule": scaleOp.Schedule,
					"jobTemplate": map[string]interface{}{
						"metadata": map[string]interface{}{
							"labels": transferLabels,
						},
						"spec": map[string]interface{}{
							"template": map[string]interface{}{
								"metadata": map[string]interface{}{
									"labels": transferLabels,
								},
								"spec": map[string]interface{}{
									"restartPolicy":  "OnFailure",
									"serviceAccount": "" + parent.Spec.TargetReference.Name + "-scaling-schedule",
									"containers": []interface{}{
										map[string]interface{}{
											"name":            "" + parent.Spec.TargetReference.Name + "-scaling-schedule",
											"image":           updateImage,
											"imagePullPolicy": "IfNotPresent",
											"command": []interface{}{
												"bash",
											},
											"args": []interface{}{
												"/update-replicas.sh",
												strings.ToLower(parent.Spec.TargetReference.Kind),
												parent.Spec.TargetReference.Name,
												scaleOp.Replicas,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		}

		resourceObj.SetNamespace(parent.Namespace)

		resourceObjects = append(resourceObjects, resourceObj)
	}

	return resourceObjects, nil
}
```
