### ISSUE TITLE
bug(yaml-parse): attempting to use network policies as resources results in error

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#189]
Attempting to use a network policy as a managed resource by operator-builder results in the following error:

```bash
FATA[0001] failed to create API: unable to inject the resource to "config.operatorbuilder.io/v1": unable to inject resource into .workload/v1alpha2/workload.yaml, error processing file resources/network-policy.yaml; error unmarshaling yaml, yaml: line 14: did not find expected '-' indicator 
```

Here is the workload config:

```yaml
---
name: tanzu-namespace
kind: StandaloneWorkload
spec:
  api:
    domain: platform.cnr.vmware.com
    group: tenancy
    version: v1alpha2
    kind: TanzuNamespace
    clusterScoped: true
  companionCliRootcmd:
    name: tanzu-ns-ctl
    description: Manage Tanzu Namespaces
  resources:
    # - resources/namespace.yaml
    # - resources/limit-range.yaml
    # - resources/resource-quota.yaml
    - resources/network-policy.yaml
```

Here is the network policy object:

```yaml
# NOTE: code markers were added before functionality for complex data types existed.  these are not functional
#       or even syntactically correct but for documentation/visualization purposes only.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "tanzu-network-policy"
  namespace: "tanzu-namespace" #+operator-builder:field:name=namespace,type=string
spec:
  podSelector:
    #+operator-builder:field:name=networkPolicy.targetPodLabels,type=string,default="",description=`
    #Labels on pods within this namespace that the network policy applies to.`
    matchLabels: ""  # this is actually a map[string]string but used to build the project for now
  ingress:
    - from:
        - namespaceSelector:

            #+operator-builder:field:name=networkPolicy.ingress.namespaceLabels,type=string,default="",description=`
            #Labels on namespaces that the ingress network policy applies to for pods which match
            #field networkPolicy.targetPodLabels.`
            matchLabels: ""  # this is actually a map[string]string but used to build the project for now

        - podSelector:

            #+operator-builder:field:name=networkPolicy.ingress.podLabels,type=string,default="",description=`
            #Labels on pods that the ingress network policy applies to for pods which match field
            #networkPolicy.targetPodLabels.`
            matchLabels: ""  # this is actually a map[string]string but used to build the project for now

    #+operator-builder:field:name=networkPolicy.ingress.ports,type=[]string,default={},description=`
    #Allowed ingress ports on matches of namespaces from field networkPolicy.ingress.namespaceLabels and
    #for pods from field networkPolicy.ingress.podLabels for pods which match field networkPolicy.targetPodLabels.`
    ports: [] # this is actually an []map[string]string but used to build the project for now
  egress:
    - to:
        - namespaceSelector:

            #+operator-builder:field:name=networkPolicy.egress.namespaceLabels,type=string,default="",description=`
            #Labels on namespaces that the egress network policy applies to for pods which match
            #field networkPolicy.targetPodLabels.`
            matchLabels: ""  # this is actually a map[string]string but used to build the project for now

        - podSelector:

            #+operator-builder:field:name=networkPolicy.egress.podLabels,type=string,default="",description=`
            #Labels on pods that the egress network policy applies to for pods which match field
            #networkPolicy.targetPodLabels.`
            matchLabels: ""  # this is actually a map[string]string but used to build the project for now

    #+operator-builder:field:name=networkPolicy.egress.ports,type=[]string,default={},description=`
    #Allowed egress ports on matches of namespaces from field networkPolicy.egress.namespaceLabels and
    #for pods from field networkPolicy.egress.podLabels.`
    ports: []  # this is actually an []map[string]string but used to build the project for now
```
