### ISSUE TITLE
Add ability to create struct types

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#2]
This allows us to nest variables.  Here is what we have currently:

```yaml
---
tanzu_workload_tenancy:
  # common vars
  namespace:      "tanzu-workload-tenancy"
  demo_namespace: "tanzu-demo"
  staging_dir:    "{{ ivy_staging_dir }}/tanzu-workload-tenancy"

  # namespace operator vars
  namespace_operator:
    # rbac
    service_account:    "namespace-operator"
    clusterrole:        "namespace-operator-clusterrole"
    clusterrolebinding: "namespace-operator-clusterrolebinding"

    # app
    image:     "projects.registry.vmware.com/cnr_project_ivy/namespace-operator"
    image_tag: "v1.2.10"
    replicas:  2
    app_name:  "namespace-operator"
```

Today, we have to do something like this to get the same effect in operator-builder:

```yaml
apiVersion: components.rpk.tanzu.vmware.com/v1alpha1
kind: WorkloadTenancy
metadata:
  name: workloadtenancy-sample
spec:
  namespace: tanzu-workload-tenancy
  globalDefaultLimitsCpu: "50m"
  globalDefaultLimitsMemory: "64Mi"
  globalDefaultRequestsCpu: "50m"
  globalDefaultRequestsMemory: "64Mi"
  globalMaxLimitsCpu: "200m"
  globalMaxLimitsMemory: "512Mi"
  globalQuotaRequestsCpu: "4"
  globalQuotaRequestsMemory: "4Gi"
  globalQuotaLimitsCpu: "4"
  globalQuotaLimitsMemory: "4Gi"
  namespaceOperatorResourceName: namespace-operator
  namespaceOperatorReplicas: 2
  namespaceOperatorRequestsCpu: "10m"
  namespaceOperatorRequestsMemory: "16Mi"
  namespaceOperatorLimitsCpu: "40m"
  namespaceOperatorLimitsMemory: "64Mi"
```

The ideal solution would be to have it look something like this:

```yaml
apiVersion: components.rpk.tanzu.vmware.com/v1alpha1
kind: WorkloadTenancy
metadata:
  name: workloadtenancy-sample
spec:
  namespace: tanzu-workload-tenancy
  namespaceOperator:
    resourceName: namespace-operator
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "16Mi"
      limits:
        cpu: "40m"
        memory: "16Mi"
...
```

It might not be hard to do something like this:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-operator #+workload:namespaceOperator.resourceName:default="namespace-operator":type=string
  annotations:
    workload.cnr.vmware.com/resource-name: namespace-operator-cluster-role
```

Where the `.` will represent another child struct.
