### ISSUE TITLE
Remove ordering requirement in the `spec.resources` field

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#209]
Currently, the code generated from the following component config will not work.  Because the `ingress-ns.yaml` namespace resource is not listed first, the creation of the contour-config will freeze and not progress.  So we currently have a requirement to list namespaces first which is a bit of a booby trap.

```
name: contour-component
kind: ComponentWorkload
spec:
  api:
    group: ingress
    version: v1alpha1
    kind: Contour
    clusterScoped: true
  companionCliSubcmd:
    name: contour
    description: Manage contour component
  resources:
  - contour-config.yaml
  - ingress-ns.yaml
  - contour-deploy.yaml
  - contour-svc.yaml
  - envoy-ds.yaml
  dependencies:
  - ns-operator-component
```
