### ISSUE TITLE
Use parent resource name as a value in a child resource

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#248]
We don't currently have a way to do this.  Consider this custom resource that is the parent:

```yaml
apiVersion: v1alpha1
kind: WebApp
metadata:
  name: intance-x
spec:
  env: dev
```

Suppose we want to deploy n number of these webapps to a single cluster - each into their own namespace.  Suppose we shove this resource into operator-builder...

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-placeholder  # +operator-builder:field:name=parent.metadata.name,type=string,replace="placeholder"
```
So, given the WebApp resource above, this would produce a namespace with name `webapp-instance-x`.

And if a WebApp with name `instance-y` was created the result would be a namespace called `webapp-instance-y`.
