### ISSUE TITLE
YAML files within configmaps inop when containing --- characters

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#26]
Given the following config map, the operator-builder fails to create the operator, due to the parsing of YAML strings within the configmap itself:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-auth-config #+workload:resourceName:default="kube-apiserver-auth-config":type=string
  namespace: cnpo-identity-system #+workload:namespace:default="cnpo-identity-system":type=string
data:
  UPDATE_K8S_CA: "true" #+workload:installCert:default="true":type=string
  kube-apiserver-config-values.yaml: |
    #@data/values
    ---
    UPDATE_K8S_CA: ""
  kube-apiserver-config-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")

    #@ def startswith(index, left, right):
    #@  return left.startswith(right)
    #@ end

    #@overlay/match by=overlay.subset({"metadata":{"labels":{"component":"kube-apiserver">>})
    ---
    spec:
      containers:
      #@overlay/match by='name', expects=1
      - name: kube-apiserver
        command:
        #@overlay/match by=startswith, missing_ok=True
        - --oidc-client-id=tanzu
        #@overlay/match by=startswith, missing_ok=True
        - --oidc-issuer-url=https://<< tanzu_identity.dex.dns >>
        #@overlay/match by=startswith, missing_ok=True
        - --oidc-username-claim=email
        #@overlay/match by=startswith, missing_ok=True
        - --oidc-groups-claim=group
        #@ if data.values.UPDATE_K8S_CA == "true":
        #@overlay/match by=startswith, missing_ok=True
        - --oidc-ca-file=/etc/kubernetes/pki/tanzu-ca.crt
        #@ end
```

Results in the following error:

```bash
panic: interface conversion: interface is nil, not interface {}

goroutine 1 [running]:
github.com/vmware-tanzu-labs/operator-builder/pkg/workload/v1.processResources(0xc000516de0, 0x5a, 0xc00062c440, 0x2, 0x4, 0x4, 0xc000af67a0, 0x0, 0x0)
        /Users/sdustin/VSCode/scottd018-github/operator-builder/pkg/workload/v1/resource.go:52 +0x114f
github.com/vmware-tanzu-labs/operator-builder/pkg/workload/v1.(*ComponentWorkload).SetResources(0xc00050f340, 0xc000516de0, 0x5a, 0x0, 0x0)
        /Users/sdustin/VSCode/scottd018-github/operator-builder/pkg/workload/v1/component.go:116 +0x65
github.com/vmware-tanzu-labs/operator-builder/pkg/workload/v1.ProcessAPIConfig(0x7ffeefbfe59d, 0x31, 0xc000019318, 0x400e48a, 0x4c20420, 0x4c50740)
        /Users/sdustin/VSCode/scottd018-github/operator-builder/pkg/workload/v1/config.go:115 +0xe45
github.com/vmware-tanzu-labs/operator-builder/pkg/plugins/config/v1.(*createAPISubcommand).InjectResource(0xc0004a9d50, 0xc00005d200, 0xc0004a9d50, 0xdfa9858)
        /Users/sdustin/VSCode/scottd018-github/operator-builder/pkg/plugins/config/v1/api.go:39 +0x3b
sigs.k8s.io/kubebuilder/v3/pkg/cli.(*executionHooksFactory).preRunEFunc.func1.2(0xdfa44c0, 0xc0004a9d50, 0x0, 0x0)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/sigs.k8s.io/kubebuilder/v3@v3.0.0/pkg/cli/cmd_helpers.go:275 +0x73
sigs.k8s.io/kubebuilder/v3/pkg/cli.(*executionHooksFactory).forEach(0xc0001bf260, 0xc00057d5b8, 0x4da650e, 0x20, 0x0, 0x0)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/sigs.k8s.io/kubebuilder/v3@v3.0.0/pkg/cli/cmd_helpers.go:198 +0x108
sigs.k8s.io/kubebuilder/v3/pkg/cli.(*executionHooksFactory).preRunEFunc.func1(0xc0003fca00, 0xc000244cc0, 0x0, 0x4, 0x0, 0x0)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/sigs.k8s.io/kubebuilder/v3@v3.0.0/pkg/cli/cmd_helpers.go:273 +0x2ae
github.com/spf13/cobra.(*Command).execute(0xc0003fca00, 0xc000244c80, 0x4, 0x4, 0xc0003fca00, 0xc000244c80)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:841 +0x530
github.com/spf13/cobra.(*Command).ExecuteC(0xc00026d400, 0x8, 0x8, 0xc0002508c0)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
sigs.k8s.io/kubebuilder/v3/pkg/cli.CLI.Run(...)
        /Users/sdustin/.gvm/pkgsets/go1.15.7/global/pkg/mod/sigs.k8s.io/kubebuilder/v3@v3.0.0/pkg/cli/cli.go:463
main.main()
        /Users/sdustin/VSCode/scottd018-github/operator-builder/cmd/main.go:59 +0x825
make: *** [operator.build.components] Error 2
```

Removing all of the `---` in the config map values proves to be successful.
