### ISSUE TITLE
bug: marker parser sees spaces in comments as multiple results

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#271]
Consider the following manifest:

```
---
# +operator-builder:resource:collectionField=provider,value="aws",include
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-config-test-collection-field
  namespace: ingress-system  # +operator-builder:field:name=namespace,default=ingress-system,type=string
data:
  this: "serves no purpose other than to test resource markers on collection fields"
---
# +operator-builder:resource:collectionField=provider,value="aws",include
# Note: Comments with spaces can cause problems with parsing.  Leave this here 
# for functional testing purposes.

# The space above is actually what causes the problem.
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-config-test-parse-comment
  namespace: ingress-system  # +operator-builder:field:name=namespace,default=ingress-system,type=string
data:
  this: "serves no purpose other than to test comment spaces for resource markers on collection fields"
```

With a space in the comment, this will actually return multiple marker results for the `contour-config-test-parse-comment` ConfigMap.  While this is not necessarily an issue if we handle the result properly, the marker package should only return one result as there is only one marker.

**Comment by scottd018** [comment]
This appears to be a bug in the upstream yaml.v3 package.  Given the above set of manifests, we get:

Manifest 0:

```yaml
---
# +operator-builder:resource:collectionField=provider,value="aws",include
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-config-test-collection-field
  namespace: ingress-system  # +operator-builder:field:name=namespace,default=ingress-system,type=string
data:
  this: "serves no purpose other than to test resource markers on collection fields"
---
# +operator-builder:resource:collectionField=provider,value="aws",include
# Note: Comments with spaces can cause problems with parsing.  Leave this here 
# for functional testing purposes.
```

Manifest 1:

```yaml
# The space above is actually what causes the problem.
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-config-test-parse-comment
  namespace: ingress-system  # +operator-builder:field:name=namespace,default=ingress-system,type=string
data:
  this: "serves no purpose other than to test comment spaces for resource markers on collection fields"
```

The newline character causes the yaml marshaler to  see the resource marker as a foot comment to the first manifest and takes the newline as the start of a new manifest.
