### ISSUE TITLE
feat: inline resources

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#292]
Add the ability to specify resources inline with the operator-builder workload configuration.  This obviously is not to encourage someone to type out an entire deployment in their workload config, rather it would be useful for something like a `Namespace` resource where one may need to be created.  That would change the spec for resources to:

```yaml
resources:
  - inline: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: my-namespace # +operator-builder:field:name=myField,default=my-namespace,type=string
  - file: path/to/another/resource.yaml
```

We should also maintain backwards compatibility and assume that the absence of a `file` or `inline` key would default to it being a `file`.  E.g. this would still be valid:

```yaml
resource:
  - path/to/legacy/resource.yaml
```
