### ISSUE TITLE
Workload Dependency Input Validation

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#33]
Given the following workload collection and component workload configs (see below), the component workloads are allowed to specify dependencies that are not a part of the workload collection.  This will result in a component which does not deploy correctly:

Collection:

```yaml
---
name: cloud-native-platform
kind: WorkloadCollection
spec:
  domain: cnpo.tanzulabs.vmware.com
  apiGroup: platform
  apiVersion: v1alpha1
  apiKind: CloudNativePlatform
  clusterScoped: true
  companionCliRootcmd:
    name: cnpo
    description: Manage Cloud Native Platform Operator
  componentFiles:
    # workload-tenancy
    - tenancy/common/config/workload.yaml
    - tenancy/namespace-operator/config/workload.yaml

    # autoscaling
    - autoscaling/common/config/workload.yaml
    - autoscaling/vertical-pod-autoscaler/config/workload.yaml
```

Component workload config with missing deps:

```yaml
---
name: vertical-pod-autoscaler-component
kind: ComponentWorkload
spec:
  apiGroup: autoscaling
  apiVersion: v1alpha1
  apiKind: VerticalPodAutoscalerComponent
  clusterScoped: true
  companionCliSubcmd:
    name: vertical-pod-autoscaler-component
    description: Manage vertical-pod-autoscaler component
  dependencies:
    - autoscaling-common-component
    - cert-manager-component
    - cluster-issuers-ca-component
  resources:
    - ../base/vpa-cert.yaml
    - ../manifests/vpa-crds.yaml
    - ../manifests/vpa-rbac.yaml
    - ../manifests/vpa-recommender-deployment.yaml
    - ../manifests/vpa-updater-deployment.yaml
    - ../manifests/vpa-admission-controller-deployment.yaml
```

The resultant go code (notice the `cert-manager-component` and `cluster-issuers-ca-component` are missing):

```go
// GetDependencies returns the dependencies for a component
func (component VerticalPodAutoscalerComponent) GetDependencies() []common.Component {
	return []common.Component{

		&AutoscalingCommonComponent{},
	}
}
```

While this will result in functional code, the workload declared dependency is non-existent in the collection which should produce an error of the effect: `missing dependency [cert-manager-component] in collection [cloud-native-platform]; needed by ComponentWorkload [vertical-pod-autoscaler-component]`.
