### ISSUE TITLE
Add ability to have multiple workload manifests in one file

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#5]
Rather than being only able to define one workload manifest per file, e.g.:

```yaml
name: webapp
spec:
  group: product
  version: v1alpha1
  kind: WebApp
  clusterScoped: false
  companionCliRootcmd:
    name: webappctl
    description: Manage webapp stuff like a boss
  resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml
```

We should be able to define multiple per file and iterate over them to create the controllers, e.g.:

```yaml
---
name: webapp
spec:
  group: product
  version: v1alpha1
  kind: WebApp
  clusterScoped: false
  companionCliRootcmd:
    name: webappctl
    description: Manage webapp stuff like a boss
  resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml
---
name: appdb
spec:
  group: product
  version: v1alpha1
  kind: AppDb
  clusterScoped: false
  companionCliRootcmd:
    name: appdbctl
    description: Manage appdb stuff like a boss
  resources:
  - statefulset.yaml
  - service.yaml
```
