### ISSUE TITLE
Add validating webhook for immutable fields

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#67]
In some cases it is not practical to reconcile an update to a field.  Example:

```
apiVersion: apps.acme.com/v1alpha1
kind: WebStore
metadata:
  name: webstore-sample
spec:
  namespace: webstore-dev
  webStoreReplicas: 2
  webStoreImage: nginx:1.17
```

Let's say we don't want to the user to be able to UPDATE the `spec.namespace` field b/c reconciling the movement of the workload to a new namespace is not worth the effort (just delete and re-deploy in new namespace).

We could potentially do this with an added `immutable` field in the workload marker:

```
apiVersion: v1
kind: Namespace
metadata:
  name: webstore-dev # +workload:namespace:type=string:immutable=true
```

When `immutable=true` is found, operator-builder could generate source code for a validating webhook to prohibit updating this field.
