### ISSUE TITLE
When using componentFiles files is relative to the collection and not the workload

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#7]
When using the `componentFiles` field in a `WorkloadCollection`, the component files are sucked in just fine, however the path of the `resources` is relative to the WorkloadCollection configuration, but should be relative to the `ComponentWorkload` configuration because the component workload is the one specifying the resources.  Here is an example:

Collection:

```yaml
---
name: cloud-native-platform
kind: WorkloadCollection
spec:
  domain: cnpo.tanzulabs.vmware.com
  apiGroup: platform
  apiVersion: v1alpha1
  apiKind: CloudNativePlatform
  clusterScoped: true
  companionCliRootcmd:
    name: cnpo
    description: Manage Cloud Native Platform Operator
  componentFiles:
    # workload-tenancy
    - tenancy/common/workload.yaml
    - tenancy/namespace-operator/workload.yaml
```

Workload:

```yaml
---
name: tenancy-common-component
kind: ComponentWorkload
spec:
  apiGroup: tenancy
  apiVersion: v1alpha1
  apiKind: TenancyCommonComponent
  clusterScoped: true
  companionCliSubcmd:
    name: tenancy-common-component
    description: Manage tenancy-common component
  dependencies: []
  resources:
    - manifests/namespace.yaml
    - manifests/default-resource-constraints.yaml
```

File tree:

```bash
tree ../cnpo.tanzulabs.vmware.com/
../cnpo.tanzulabs.vmware.com/
├── collection.yaml
└── tenancy
    ├── common
    │   ├── manifests
    │   │   ├── default-resource-constraints.yaml
    │   │   └── namespace.yaml
    │   └── workload.yaml
```
