### ISSUE TITLE
Improve status.conditions Fields

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#80]
Currently, these are tied to phases, however we should track status on resources as well (we do get certain info from resources but this should be split out into a separate condition).

```yaml
    conditions:
    - message: Completed Phase Dependency
      phase: Dependency
      status: "True"
      type: Reconciling
    - message: Completed Phase PreFlight
      phase: PreFlight
      status: "True"
      type: Reconciling
    - message: Created tanzunamespaces.tenancy.platform.cnr.vmware.com CustomResourceDefinition
      phase: CreateResources
      status: "True"
      type: Reconciling
    - message: Created namespace-operator ServiceAccount
      phase: CreateResources
      status: "True"
      type: Reconciling
    - message: Created namespace-operator ClusterRole
      phase: CreateResources
      status: "True"
      type: Reconciling
    - message: Created namespace-operator ClusterRoleBinding
      phase: CreateResources
      status: "True"
      type: Reconciling
    - message: Created namespace-operator Deployment
      phase: CreateResources
      status: "True"
      type: Reconciling
    - message: Completed Phase CreateResources
      phase: CreateResources
      status: "True"
      type: Reconciling
    - message: Completed Phase CheckReady
      phase: CheckReady
      status: "True"
      type: Reconciling
    - message: Completed Phase Complete; Resource is Ready
      phase: Complete
      status: "True"
      type: Ready
    created: true
```
